name: Build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  HUSKY: 0

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Check format
        run: dotnet format --no-restore --verify-no-changes
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --logger trx --collect "XPlat Code Coverage"
      - name: Test report
        uses: bibipkins/dotnet-test-reporter@v1.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Test results
          results-path: ./**/TestResults/*.trx
          coverage-path: ./**/TestResults/coverage*.xml
          coverage-threshold: 80