name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  HUSKY: 0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Check format
        run: dotnet format --no-restore --verify-no-changes
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal